server:
  port: 8081
  servlet:
    context-path: /picpay/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: zieltech
    password: zieltech
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    create-schemas: true
    schemas: dev

logging:
  level:
    org:
      flywaydb:
        core: debug
      hibernate:
        SQL: debug
